import type { PLMNode, PLMEdge } from '../types';

export const initialNodes: PLMNode[] = [
  {
    id: '1',
    type: 'custom',
    position: { x: 50, y: 200 },
    data: {
      label: 'Propulsion Control System',
      type: 'system',
      itemType: 'system',
      reqId: 'SYS-001',
      version: '1.0',
      classification: 'system',
      description: 'Main propulsion control system for vessel motor management',
      rationale: 'Required to control and monitor all propulsion motors on the vessel',
      priority: 'high',
      status: 'in-progress',
      state: 'open',
      owner: 'Systems Engineering',
      attachment: null,
    },
  },
  {
    id: '2',
    type: 'custom',
    position: { x: 350, y: 80 },
    data: {
      label: 'Motor Controller',
      type: 'subsystem',
      itemType: 'subsystem',
      reqId: 'SUB-001',
      version: '1.0',
      classification: 'subsystem',
      description: 'Controls motor speed and direction',
      rationale: 'Needed to translate bridge commands to motor actions',
      priority: 'high',
      status: 'in-progress',
      state: 'open',
      owner: 'Control Systems Team',
      attachment: null,
    },
  },
  {
    id: '3',
    type: 'custom',
    position: { x: 350, y: 320 },
    data: {
      label: 'Safety Monitor',
      type: 'subsystem',
      itemType: 'subsystem',
      reqId: 'SUB-002',
      version: '1.0',
      classification: 'subsystem',
      description: 'Monitors safety conditions and triggers emergency stops',
      rationale: 'Critical for vessel and crew safety - IMO requirement',
      priority: 'high',
      status: 'new',
      state: 'frozen',
      owner: 'Safety Team',
      attachment: null,
    },
  },
  {
    id: '4',
    type: 'custom',
    position: { x: 650, y: 30 },
    data: {
      label: 'Speed Regulation',
      type: 'function',
      itemType: 'function',
      reqId: 'FUN-001',
      version: '1.0',
      classification: 'function',
      description: 'Regulate motor speed from 0-100%',
      rationale: 'Core function for vessel maneuverability',
      priority: 'high',
      status: 'in-progress',
      state: 'open',
      owner: 'Software Team',
      attachment: null,
    },
  },
  {
    id: '5',
    type: 'custom',
    position: { x: 650, y: 180 },
    data: {
      label: 'Direction Control',
      type: 'function',
      itemType: 'function',
      reqId: 'FUN-002',
      version: '1.0',
      classification: 'function',
      description: 'Control forward/reverse direction',
      rationale: 'Essential for docking and maneuvering',
      priority: 'high',
      status: 'new',
      state: 'open',
      owner: 'Software Team',
      attachment: null,
    },
  },
  {
    id: '6',
    type: 'custom',
    position: { x: 650, y: 320 },
    data: {
      label: 'Emergency Stop',
      type: 'function',
      itemType: 'function',
      reqId: 'FUN-003',
      version: '1.0',
      classification: 'function',
      description: 'Immediately stop all motors within 2 seconds',
      rationale: 'Safety critical - required by maritime regulations',
      priority: 'high',
      status: 'in-progress',
      state: 'frozen',
      owner: 'Safety Team',
      attachment: null,
    },
  },
  {
    id: '7',
    type: 'custom',
    position: { x: 950, y: 30 },
    data: {
      label: 'PWM Control Algorithm',
      type: 'project',
      reqType: 'project',
      reqId: 'PRJ-001',
      version: '1.0',
      classification: 'requirement',
      description: 'Implement PWM control with 10kHz frequency',
      rationale: 'Required for smooth speed transitions',
      priority: 'high',
      status: 'new',
      state: 'open',
      owner: 'Fredrik',
      attachment: null,
    },
  },
  {
    id: '8',
    type: 'custom',
    position: { x: 950, y: 180 },
    data: {
      label: 'Direction State Machine',
      type: 'project',
      reqType: 'project',
      reqId: 'PRJ-002',
      version: '1.0',
      classification: 'requirement',
      description: 'Implement state machine for direction changes with safety interlocks',
      rationale: 'Prevent mechanical damage from sudden direction changes',
      priority: 'medium',
      status: 'new',
      state: 'open',
      owner: 'Fredrik',
      attachment: null,
    },
  },
  {
    id: '9',
    type: 'custom',
    position: { x: 950, y: 320 },
    data: {
      label: 'Hardware Interrupt Handler',
      type: 'project',
      reqType: 'implementation',
      reqId: 'IMP-001',
      version: '1.0',
      classification: 'requirement',
      description: 'Implement interrupt-based stop signal with <10ms latency',
      rationale: 'Ensures immediate response to emergency stop commands',
      priority: 'high',
      status: 'in-progress',
      state: 'open',
      owner: 'Embedded Team',
      attachment: null,
    },
  },
  {
    id: '10',
    type: 'custom',
    position: { x: 50, y: 450 },
    data: {
      label: 'Vessel Speed Control',
      type: 'platform',
      reqType: 'customer',
      reqId: 'CUS-001',
      version: '1.0',
      classification: 'need',
      description: 'Customer requires precise vessel speed control for fuel efficiency',
      rationale: 'Customer business requirement - reduce fuel costs by 15%',
      priority: 'high',
      status: 'done',
      state: 'released',
      owner: 'Customer: Nordic Shipping AB',
      attachment: null,
    },
  },
];

export const initialEdges: PLMEdge[] = [
  { id: 'e1-2', source: '1', target: '2', type: 'custom', data: { relationType: 'contains', notes: 'Motor Controller is part of the main propulsion system' } },
  { id: 'e1-3', source: '1', target: '3', type: 'custom', data: { relationType: 'contains', notes: 'Safety Monitor is integrated into propulsion system' } },
  { id: 'e2-4', source: '2', target: '4', type: 'custom', data: { relationType: 'provides', notes: 'Motor Controller provides speed regulation capability' } },
  { id: 'e2-5', source: '2', target: '5', type: 'custom', data: { relationType: 'provides', notes: 'Motor Controller handles direction switching' } },
  { id: 'e3-6', source: '3', target: '6', type: 'custom', data: { relationType: 'provides', notes: 'Safety Monitor triggers emergency stop function' } },
  { id: 'e4-7', source: '4', target: '7', type: 'custom', data: { relationType: 'realizedBy', notes: 'PWM algorithm implements speed regulation' } },
  { id: 'e5-8', source: '5', target: '8', type: 'custom', data: { relationType: 'realizedBy', notes: 'State machine implements direction control logic' } },
  { id: 'e6-9', source: '6', target: '9', type: 'custom', data: { relationType: 'realizedBy', notes: 'Interrupt handler implements emergency stop response' } },
  { id: 'e10-1', source: '10', target: '1', type: 'custom', data: { relationType: 'satisfies', notes: 'Propulsion Control System satisfies customer speed control needs' } },
];
